services:
  drone-srcb:
    build: .
    environment:
      API_ID: $API_ID  
      API_HASH: $API_HASH  
      BOT_TOKEN: $BOT_TOKEN 
      BOT_OWNER: $BOT_OWNER
      CLIENT_ID: $CLIENT_ID
      CLIENT_SECRET: $CLIENT_SECRET
    ports:
      - 8080
    resources:
      cpu: 1000m
      memory: 3Gi
